require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.1
  NewCops: enable
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'test/**/*'
  - 'bin/**/*'

Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/integration/**/*'
RSpec/ExampleLength:
  Max: 10
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 10
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/integration/**/*'
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - 'spec/**/*.rb'
